# Generated by Django 5.0.7 on 2024-07-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date_creation",
            field=models.DateField(verbose_name="Дата создания"),
        ),
    ]
