# Generated by Django 4.2.2 on 2024-08-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("message", models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="version",
            options={
                "ordering": ["indication_current_version", "version_number"],
                "verbose_name": "Версия продукта",
                "verbose_name_plural": "Версии продуктов",
            },
        ),
        migrations.RemoveField(
            model_name="version",
            name="category",
        ),
        migrations.RemoveField(
            model_name="version",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="version",
            name="name",
        ),
        migrations.RemoveField(
            model_name="version",
            name="price",
        ),
        migrations.RemoveField(
            model_name="version",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="version",
            name="indication_current_version",
            field=models.BooleanField(
                default=False,
                help_text="Введите признак текущей версии",
                verbose_name="Признак текущей версии.",
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="version_name",
            field=models.CharField(
                blank=True,
                help_text="Введите название версии",
                null=True,
                verbose_name="Название версии",
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="version_number",
            field=models.PositiveIntegerField(
                default=1, help_text="Введите номер версии", verbose_name="Номер версии"
            ),
            preserve_default=False,
        ),
    ]
